import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@/ELEMENTX/abstract/abstract.css';
import Nav from "@/components/nav/Nav";
import ThemeContext from "@/feature/themeContext/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="mega-trans" lang="en">
      <head>
      {/* <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script> */}
      </head>
      <body className={inter.className}>
        {children}
        </body>
    </html>
  );
}
